/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clienteservidor;

import static clienteservidor.Cliente.servico;
import static clienteservidor.Cliente.servico2;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.sql.SQLException;
import java.util.Random;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 *
 * @author willi
 */
public class TelaCadastro extends javax.swing.JFrame {

    JPasswordField senha = new JPasswordField();
    JPasswordField senha2 = new JPasswordField();

    public TelaCadastro() {
        initComponents();

        this.senha.setBounds(6, 100, 100, 30);
        this.senha2.setBounds(6, 162, 100, 30);
        this.add(senha);
        this.add(senha2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome");

        jLabel2.setText("Senha");

        jLabel3.setText("Senha novamente");

        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textNome, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(26, 26, 26)
                .addComponent(btCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(btCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed

        String nome = this.textNome.getText();
        String senha = this.senha.getText();
        String senha2 = this.senha2.getText();
        String agencia = "";

        if (!this.textNome.getText().trim().equals("") && !this.senha.getText().trim().equals("") && !this.senha2.getText().trim().equals("")) {
            if (senha.equals(senha2)) {
                try {
                    System.out.println("Entrou aqui");
                    UUID uuid = UUID.randomUUID();
                    String myRandom = uuid.toString();
                    Random rand = new Random();
                    int x = rand.nextInt();
                    System.out.println("Passa aqui");
                    if (x < 0) {
                        x = x * -1;
                    }
                    System.out.println("Valor de x " + x);
                    if (x % 2 != 1) {
                        System.out.println("par");
                        agencia = "2";
                        System.out.println(agencia);
                    }
                    if (x % 2 != 0) {
                        System.out.println("impar");
                        agencia = "1";
                    }
                    if (agencia.equals("1")) {
                        servico.gravarDados(nome, myRandom.substring(0, 15), "0", senha, "1");
                        System.out.println("Foi para agencia 1");
                        JOptionPane.showMessageDialog(null, "Usuario novo adicionado, agencia 1, reinicie o sistema e entre com sua conta nova, o numero da sua conta é " + myRandom.substring(0, 15));
                        System.exit(0);
                    }
                    if (agencia.equals("2")) {
                        servico2.gravarDados(nome, myRandom.substring(0, 15), "0", senha, "2");
                        System.out.println("Foi para agencia 2");
                        JOptionPane.showMessageDialog(null, "Usuario novo adicionado, agencia 2, reinicie o sistema e entre com sua conta nova, o numero da sua conta é " + myRandom.substring(0, 15));
                        System.exit(0);
                    }

                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Erro no sistema, tente mais tarde");
                } catch (RemoteException ex) {
                    Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
                }
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(null, "Senhas diferentes");
            }
        } else {
            JOptionPane.showMessageDialog(null, "E necessario entrar com os valores nos campos de texto para cadastro..");
            return;
        }

    }//GEN-LAST:event_btCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cliente dialog = null;
                try {
                    dialog = new Cliente(new javax.swing.JFrame(), true);
                } catch (RemoteException ex) {
                    Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);

                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField textNome;
    // End of variables declaration//GEN-END:variables
}
